/**
 * `InternalOAuthError` error.
 *
 * InternalOAuthError wraps errors generated by node-oauth.  By wrapping these
 * objects, error messages can be formatted in a manner that aids in debugging
 * OAuth issues.
 */
declare class InternalOAuthError extends Error {
  message: string;
  err: Error;
  constructor (message: string, err: Error);
}

export = InternalOAuthError;
